openapi: 3.0.1
info:
  title: API Hub Credentials API
  description: |
    This is used by the HIP Platform to pull updates and state
    of credentials

    ```
    Change Log
    
    ```

      | Version | Date | Author | Description |
      |---|-----|------|-----|
      | 1.0.0 | 11-12-2022 | Adam Pridmore | Initial draft |
      | 1.0.1 | 06-01-2023 | Mark Stead/Adam Pridmore | Added error responses and examples |
      | 1.0.2 | 09-01-2023 | Mark Stead | Added change log |     

  version: "1.0"

servers: 
  - url: https://api-hub-credentials-api.protected.mdtp/api
  
    description: |
      **TODO** The production URL for getting access to the HIP Portal API

# This defines the default security and scopes if an endpoint doesn't define one
security: 
  - OAuth2:
    - credentialsRead

paths:
  /v1/environments/{environment-id}/credentials/:
    get:
      summary: Get all credentials
      description: |
        Returns all the credentials and associated scopes for 
        an environment.
        
        # Phase 1 - Get all credentials
        
        Get all the credentials for an environment
        
        # Phase 2 - Add support for 'ETags'

        Return ETag header in the response payload
        HIP API Platform will poll this endpoint with the ETag of the last request
         - If ETag is missing return all credentials (same as ETag doesn't
          match). Used as part of a cold start up
         - If ETag matches (e.g. there are no changes) return 304 (Not Modified) status
         - If ETag doesn't match (e.g. there are changes) return all credentials (and API Platform will sync all credentials)
      security:
        - OAuth2:
          - registrationsCredentialsRead
      tags:
        - Credentials
      parameters:
        - in: path
          name: environment-id
          schema:
            type: string
            example: production
          required: true
      responses:
        200:
          description: A list of credentials to scope mappings
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Credentials"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                {
                  "code": "BAD_REQUEST",
                  "message": "TBD"
                }
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                {
                  "code": "UNAUTHORIZED",
                  "message": "Invalid OAuth token supplied"
                }
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                {
                  "code": "FORBIDDEN",
                  "message": "Supplied OAuth token not authorised to access the API"
                }
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                {
                  "code": "NOT_FOUND",
                  "message": "The resource '/v1/environments/bad-env/credentials' could not be found"
                }
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                {
                  "code": "INTERNAL_SERVER_ERROR",
                  "message": "Internal Server Error"
                }
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: |
        **TODO**: Need to correctly populate the token endpoint below.
      flows:
        clientCredentials:
          tokenUrl: https://api-hub-credentials-api.protected.mdtp/token
          scopes:
            credentialsRead: Get credential secrets

  schemas:
    Credentials:
      type: array
      items:
        $ref: "#/components/schemas/Credential"
      example:
        [
          {
            "clientId": "f8b71f85-7a5a-4389-8c55-0623dc6859fb",
            "clientSecret" : "N1okR3lmb1J4QThoIUBjbjVXams",
            "scopes" : [
              "scope-1",
              "scope-2"
            ]
          }, {
            "clientId": "260ef253-f24d-4186-8b3a-0d45409af1c3",
            "clientSecret" : "NGU5ZWU0ODAtNjBmNC0xMWVkLTliNmE",
            "scopes" : [
              "scope-2",
              "scope-3"
            ]
          }
        ]
    Credential:
      type: object
      properties:
        clientId:
          type: string
        clientSecret:
          type: string
        scopes:
          type: array
          items:
            type: string
  
    ErrorResponse:
      description: Schema defining the format of the error response
      type: object
      properties:
        code:
          description: A code identifying the type of error
          type: string
        message:
          description: A summary message indicating what the error is
          type: string

